[functions.discord-interactions]
verify_jwt = false

[functions.notify-discord]
verify_jwt = false

[functions.submit-request]
verify_jwt = false

[functions.close-threads]
verify_jwt = false

[functions.discord-oauth]
verify_jwt = false

[functions.post-poster]
verify_jwt = false

[functions.update-request-status]
verify_jwt = false

[functions.submit-list-items]
verify_jwt = false

[functions.update-list-item]
verify_jwt = false
