import { UnmatchedStats } from '../api/client'

type ToastType = 'success' | 'error' | 'info'
export type UnmatchedDownloadType = 'movies' | 'series' | 'seasons' | 'collections'

interface UsePosterManagerUnmatchedReportsParams {
  unmatchedStats: UnmatchedStats | null
  showToast: (message: string, type?: ToastType) => void
  // Asset type the stats describe ('Posters', 'Logos', ...), so reports name what's
  // actually missing instead of always saying posters.
  typeNoun?: string
}

const formatPercent = (percent: number): string => {
  if (percent === 100) {
    return '100.0'
  } else if (percent >= 99.95) {
    return percent.toFixed(2)
  }
  return percent.toFixed(1)
}

const downloadTextFile = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export const usePosterManagerUnmatchedReports = ({
  unmatchedStats,
  showToast,
  typeNoun = 'Posters',
}: UsePosterManagerUnmatchedReportsParams) => {
  const noun = typeNoun.toLowerCase()
  const NOUN = typeNoun.toUpperCase()
  const slug = noun.replace(/\s+/g, '-')
  // Artwork has no season dimension, so "main" only means something for posters.
  const hasSeasons = Boolean(unmatchedStats?.summary?.seasons && unmatchedStats.summary.seasons.total > 0)

  const downloadUnmatchedList = (type: UnmatchedDownloadType) => {
    if (!unmatchedStats || !unmatchedStats.unmatched) return

    let content = ''
    let filename = ''
    const timestamp = new Date().toISOString().split('T')[0]

    if (type === 'movies' && unmatchedStats.unmatched.movies) {
      const items = unmatchedStats.unmatched.movies
      filename = `unmatched-${slug}-movies-${timestamp}.txt`
      content = `UNMATCHED MOVIES - ${timestamp}\n`
      content += `Generated by PosterFlow\n`
      content += `Total: ${items.length} movies without ${noun}\n`
      content += `${'='.repeat(60)}\n\n`

      items.forEach((item, idx) => {
        content += `${idx + 1}. ${item.title}`
        if (item.year) content += ` (${item.year})`
        if (item.instance) content += ` [${item.instance}]`
        content += `\n`
      })
    } else if (type === 'series' && unmatchedStats.unmatched.series) {
      const items = unmatchedStats.unmatched.series.filter(s => s.missing_main_poster)
      filename = `unmatched-${slug}-series-${timestamp}.txt`
      content = `UNMATCHED SERIES (Missing ${hasSeasons ? 'Main ' : ''}${typeNoun}) - ${timestamp}\n`
      content += `Generated by PosterFlow\n`
      content += `Total: ${items.length} series without ${hasSeasons ? 'main ' : ''}${noun}\n`
      content += `${'='.repeat(60)}\n\n`

      items.forEach((item, idx) => {
        content += `${idx + 1}. ${item.title}`
        if (item.year) content += ` (${item.year})`
        if (item.instance) content += ` [${item.instance}]`
        content += `\n`
      })
    } else if (type === 'seasons' && unmatchedStats.unmatched.series) {
      const items = unmatchedStats.unmatched.series.filter(s => s.missing_seasons.length > 0)
      filename = `unmatched-${slug}-seasons-${timestamp}.txt`
      content = `UNMATCHED SEASONS - ${timestamp}\n`
      content += `Generated by PosterFlow\n`
      content += `Total: ${items.length} series with missing season ${noun}\n`
      content += `${'='.repeat(60)}\n\n`

      items.forEach((item, idx) => {
        content += `${idx + 1}. ${item.title}`
        if (item.year) content += ` (${item.year})`
        content += `\n`
        content += `   Missing Seasons: ${item.missing_seasons.map(s => `S${s}`).join(', ')}`
        if (item.instance) content += ` [${item.instance}]`
        content += `\n\n`
      })
    } else if (type === 'collections' && unmatchedStats.unmatched.collections) {
      const items = unmatchedStats.unmatched.collections
      filename = `unmatched-${slug}-collections-${timestamp}.txt`
      content = `UNMATCHED COLLECTIONS - ${timestamp}\n`
      content += `Generated by PosterFlow\n`
      content += `Total: ${items.length} collections without ${noun}\n`
      content += `${'='.repeat(60)}\n\n`

      items.forEach((item, idx) => {
        content += `${idx + 1}. ${item.title}`
        if (item.instance) content += ` [${item.instance}]`
        content += `\n`
      })
    }

    downloadTextFile(content, filename)
    showToast(`Downloaded ${filename}`)
  }

  const downloadCompleteReport = () => {
    if (!unmatchedStats || !unmatchedStats.unmatched) return

    const timestamp = new Date().toISOString().split('T')[0]
    const filename = `unmatched-${slug}-complete-report-${timestamp}.txt`
    let content = ''

    content += `POSTERFLOW - COMPLETE UNMATCHED ${NOUN} REPORT\n`
    content += `Generated: ${new Date().toLocaleString()}\n`
    content += `${'='.repeat(70)}\n\n`

    content += `SUMMARY\n`
    content += `${'-'.repeat(70)}\n`
    content += `Total Items: ${unmatchedStats.summary.grand_total.total}\n`
    content += `With ${typeNoun}: ${unmatchedStats.summary.grand_total.total - unmatchedStats.summary.grand_total.unmatched}\n`
    content += `Missing ${typeNoun}: ${unmatchedStats.summary.grand_total.unmatched}\n`
    content += `Coverage: ${formatPercent(unmatchedStats.summary.grand_total.percent_complete)}%\n\n`

    if (unmatchedStats.unmatched.movies && unmatchedStats.unmatched.movies.length > 0) {
      content += `\n${'='.repeat(70)}\n`
      content += `MOVIES WITHOUT ${NOUN} (${unmatchedStats.unmatched.movies.length})\n`
      content += `${'='.repeat(70)}\n\n`
      unmatchedStats.unmatched.movies.forEach((item, idx) => {
        content += `${idx + 1}. ${item.title}`
        if (item.year) content += ` (${item.year})`
        if (item.instance) content += ` [${item.instance}]`
        content += `\n`
      })
    }

    const seriesWithoutMain = unmatchedStats.unmatched.series?.filter(s => s.missing_main_poster) || []
    if (seriesWithoutMain.length > 0) {
      content += `\n${'='.repeat(70)}\n`
      content += `SERIES WITHOUT ${hasSeasons ? 'MAIN ' : ''}${NOUN} (${seriesWithoutMain.length})\n`
      content += `${'='.repeat(70)}\n\n`
      seriesWithoutMain.forEach((item, idx) => {
        content += `${idx + 1}. ${item.title}`
        if (item.year) content += ` (${item.year})`
        if (item.instance) content += ` [${item.instance}]`
        content += `\n`
      })
    }

    const seriesWithMissingSeasons = unmatchedStats.unmatched.series?.filter(s => s.missing_seasons.length > 0) || []
    if (seriesWithMissingSeasons.length > 0) {
      content += `\n${'='.repeat(70)}\n`
      content += `SERIES WITH MISSING SEASON ${NOUN} (${seriesWithMissingSeasons.length})\n`
      content += `${'='.repeat(70)}\n\n`
      seriesWithMissingSeasons.forEach((item, idx) => {
        content += `${idx + 1}. ${item.title}`
        if (item.year) content += ` (${item.year})`
        content += `\n`
        content += `   Missing Seasons: ${item.missing_seasons.map(s => `S${s}`).join(', ')}`
        if (item.instance) content += ` [${item.instance}]`
        content += `\n\n`
      })
    }

    if (unmatchedStats.unmatched.collections && unmatchedStats.unmatched.collections.length > 0) {
      content += `\n${'='.repeat(70)}\n`
      content += `COLLECTIONS WITHOUT ${NOUN} (${unmatchedStats.unmatched.collections.length})\n`
      content += `${'='.repeat(70)}\n\n`
      unmatchedStats.unmatched.collections.forEach((item, idx) => {
        content += `${idx + 1}. ${item.title}`
        if (item.instance) content += ` [${item.instance}]`
        content += `\n`
      })
    }

    content += `\n${'='.repeat(70)}\n`
    content += `END OF REPORT\n`

    downloadTextFile(content, filename)
    showToast(`Downloaded complete report: ${filename}`)
  }

  return {
    downloadUnmatchedList,
    downloadCompleteReport,
  }
}
