export {
  type Drive,
  createCustomDrive,
  deleteDrive,
  getDrives,
  reloadDrives,
  subscribeDrive,
  unsubscribeDrive,
  updateDrive,
} from './drives'

export {
  type ArtworkUnmatchedStats,
  type ArtworkType,
  getArtworkUnmatchedStats,
} from './artwork_unmatched'

export {
  type ArtworkDrive,
  type ArtworkDrivePriority,
  ARTWORK_TYPES,
  ARTWORK_TYPE_LABELS,
  ARTWORK_TYPE_FOLDERS,
  createCustomArtworkDrive,
  deleteArtworkDrive,
  getArtworkDrives,
  reloadArtworkDrives,
  subscribeArtworkDrive,
  unsubscribeArtworkDrive,
  updateArtworkDrive,
  syncArtworkDrive,
  syncAllArtworkDrives,
  getArtworkDrivePriority,
  saveArtworkDrivePriority,
} from './artwork_drives'

export {
  type Job,
  type JobLogFile,
  type JobLogs,
  cancelJob,
  connectJobLogLiveWS,
  downloadJobLog,
  getJob,
  getJobLogContent,
  getJobLogs,
  getJobs,
  startIdarr,
  startIdarrSync,
  startSync,
  startSyncAll,
} from './jobs'

export {
  type LogEntry,
  type LogHistoryPage,
  type LogSearchResult,
  clearLogs,
  getDebugStatus,
  getLogHistory,
  getLogs,
  searchLogs,
  toggleDebug,
} from './logs'

export {
  type DatabaseStats,
  cleanupDatabase,
  downloadBackup,
  getDatabaseStats,
  saveBackupToLocation,
  uploadBackup,
} from './maintenance'

export {
  type DiscordNotificationConfig,
  type DiscordNotificationFeatureConfig,
  type MakerIdarrCacheStats,
  type MakerIdarrConfig,
  type MakerIdarrIgnoredItem,
  type MakerIdarrLastRun,
  type MakerIdarrPendingCandidate,
  type MakerIdarrPendingItem,
  type MakerIdarrResolutionEvent,
  type MakerIdarrRunOutcome,
  type MakerIdarrRunResult,
  type MakerIdarrSyncTarget,
  type PlexLibrary,
  type PlexLibraryConfig,
  addMakerIdarrIgnoredTitle,
  checkSetupComplete,
  clearMakerIdarrPendingMatches,
  getDiscordNotificationConfig,
  getMakerIdarrCacheStats,
  getMakerIdarrConfig,
  getMakerIdarrIgnoredTitles,
  getMakerIdarrLastRun,
  getMakerIdarrPendingCandidates,
  getMakerIdarrPendingCount,
  getMakerIdarrPendingMatches,
  getMakerIdarrRunResult,
  getJellyfinLibraries,
  getPlexLibraries,
  getPlexLibraryConfigs,
  archiveIdarrSourceFile,
  getSettings,
  importMakerIdarrIgnoredTitles,
  removeMakerIdarrIgnoredTitle,
  replaceMakerIdarrIgnoredTitles,
  revealSensitiveSetting,
  resolveMakerIdarrPendingMatch,
  revertMakerIdarrLatestRun,
  reviewMakerIdarrPendingCandidate,
  runMakerIdarrCacheMaintenance,
  saveBulkSettings,
  saveDiscordNotificationConfig,
  saveMakerIdarrConfig,
  savePlexLibraryConfig,
  saveSettings,
  getGdriveStoragePath,
  saveGdriveStoragePath,
  getArtworkGdriveStoragePath,
  saveArtworkGdriveStoragePath,
  type BackupStorageSettings,
  getBackupStorage,
  saveBackupStorage,
  testDiscordNotification,
  testJellyfin,
  testPlex,
  testRadarr,
  testSonarr,
  uploadMakerIdarrFiles,
  uploadServiceAccountJson,
} from './settings'

export {
  type PosterActivityStats,
  type RecentSyncedPoster,
  type Schedule,
  type Stats,
  createSchedule,
  deleteSchedule,
  getPosterActivityStats,
  getRecentSyncedPosters,
  getSchedules,
  getStats,
  updateSchedule,
} from './schedules'

export {
  DEFAULT_POSTER_DESTINATION,
  type FlowConfig,
  type FlowResult,
  type IdarrFlowJobConfig,
  type PosterConfig,
  type MatchReport,
  type MatchReportCandidate,
  type MatchReportResponse,
  type MatchReportVerdict,
  type PosterSearchItem,
  type TmdbCandidate,
  type UnmatchedIgnoreItem,
  type UnmatchedStats,
  type Workflow,
  addUnmatchedIgnoreItem,
  createWorkflow,
  deleteWorkflow,
  downloadMatchReport,
  fetchUnmatchedMatchReport,
  getDrivePriority,
  getFlowConfig,
  getPosterConfig,
  getUnmatchedIgnoreItems,
  getUnmatchedStats,
  listWorkflows,
  removeUnmatchedIgnoreItem,
  runBorderReplacer,
  runFlow,
  saveDrivePriority,
  saveFlowConfig,
  savePosterConfig,
  searchPosters,
  searchUnmatchedTmdb,
  startAssetRename,
  startPosterRename,
  startUnmatchedDetection,
  updateWorkflow,
} from './posterManager'

export {
  type PlexUploadCacheSummary,
  type PlexUploadLibraryConfig,
  type PlexUploadInstanceMap,
  type PlexUploadInstanceMapEntry,
  type PlexSearchItem,
  type PlexWebhookDedupeEntry,
  type PlexWebhookStats,
  getPlexUploadInstanceMap,
  savePlexUploadInstanceMap,
  clearPlexUploadCache,
  clearPlexWebhookDedupe,
  downloadPlexUploadCacheExport,
  getPlexManualSettings,
  getPlexUploadCache,
  getPlexUploadCacheEntries,
  getPlexUploadLibraryOverrideSettings,
  getPlexWebhookDedupeEntries,
  getPlexWebhookSettings,
  getPlexWebhookStats,
  getPlexWebhookToken,
  regeneratePlexWebhookToken,
  resetPlexWebhookStats,
  runPlexSingleUpload,
  runPlexUpload,
  savePlexManualSettings,
  savePlexUploadLibraryOverrideSettings,
  savePlexWebhookSettings,
  searchPlexItems,
} from './plexUpload'

export {
  type MakerMonitorConfig,
  type MakerMonitorRunQueuedResponse,
  type MakerMonitorRunResponse,
  type PsdExportRequest,
  type TmdbImage,
  type TmdbImagesResponse,
  type TmdbSearchFilter,
  type TmdbSearchResult,
  type TmdbSearchIds,
  type TmdbSeasonInfo,
  type TmdbTvDetails,
  type PsdExportResult,
  type PsdExportNotFound,
  type PosterAvailability,
  type PosterStyleEntry,
  exportToPsd,
  posterLayerNames,
  openPhotopeaWithPsd,
  enqueuePhotoshopOpen,
  downloadPhotoshopPlugin,
  uploadPsdToExportFolder,
  checkTmdbPosterAvailability,
  getMakerMonitorConfig,
  getMakerMonitorLastResult,
  getMakerMonitorNeededCount,
  getSeasonImages,
  getTmdbImages,
  getTmdbImageProxyUrl,
  getTmdbOriginCountry,
  getTmdbOverview,
  getTvDetails,
  type ImageSource,
  getTvdbImages,
  getTvdbSeasonImages,
  getFanartImages,
  getFanartSeasonImages,
  getTvdbImageProxyUrl,
  getFanartImageProxyUrl,
  fanartPreviewUrl,
  runMakerMonitor,
  saveMakerMonitorConfig,
  searchTmdb,
  type ArtworkSubtype,
  type ArtworkListType,
  type ArtworkCandidate,
  type ArtworkCandidatesResponse,
  type ArtworkItemRef,
  type AddArtworkRequest,
  type AddArtworkResponse,
  type CropArtworkRequest,
  type ArtworkPullSource,
  type ArtworkPullRequest,
  type ArtworkScopeItem,
  type ArtworkItemSource,
  getArtworkScopeItems,
  getArtworkCandidates,
  addArtwork,
  cropArtworkSquare,
  startArtworkPull,
  getGracenoteImageProxyUrl,
  getArtworkTaggedDownloadUrl,
  type SaveGalleryArtworkResponse,
  saveGalleryArtworkToFolder,
  type LocalArtworkFile,
  type LocalArtworkSource,
  type LocalArtworkFolderResponse,
  type AddLocalArtworkRequest,
  getLocalArtworkFolder,
  setLocalArtworkFolder,
  getLocalArtworkImageUrl,
  addLocalArtwork,
  type TextLogoFields,
  type TextLogoRenderOptions,
  type TextLogoRenderRequest,
  type TextLogoFont,
  listTextLogoFonts,
  type AddTextLogoRequest,
  defaultTextLogoFields,
  previewTextLogo,
  addTextLogo,
} from './makerTools'

export {
  type CommunityRequest,
  type SubmitRequestPayload,
  type SubmitRequestResponse,
  type CommunityListItem,
  type ListItemInput,
  type SubmitListItemsPayload,
  type SubmitListItemsResponse,
  getCommunityRequests,
  getCommunityRequestCount,
  getMyCommunityRequestCounts,
  submitCommunityRequest,
  getCommunityListItems,
  submitCommunityListItems,
} from './community'

export const getApiErrorMessage = (error: unknown, fallback: string): string => {
  const maybeError = error as {
    response?: { data?: { detail?: string } }
    message?: string
  }

  const detail = maybeError?.response?.data?.detail
  if (typeof detail === 'string' && detail.trim()) {
    return detail
  }

  const message = maybeError?.message
  if (typeof message === 'string' && message.trim()) {
    return message
  }

  return fallback
}

// Helper to get WebSocket URL from API URL
export const getWebSocketUrl = () => {
  // Always recalculate at runtime to avoid stale values
  const apiUrl = import.meta.env.VITE_API_URL || window.location.origin
  const url = new URL(apiUrl)
  const protocol = url.protocol === 'https:' ? 'wss:' : 'ws:'
  const wsUrl = `${protocol}//${url.host}/api/jobs/ws`
  return wsUrl
}

const JOB_TYPE_LABELS: Record<string, string> = {
  gdrive_sync: 'Poster Drive Sync',
  sync: 'Poster Drive Sync',
  sync_all: 'Poster Drive Sync (All)',
  artwork_sync: 'Artwork Drive Sync',
  poster_workflow: 'Poster Workflow',
  poster_renamer: 'Asset Renamer',
  'Poster Renamer': 'Asset Renamer',
  // Persisted job types keep the historical Plex names; display as Asset Upload
  'Plex Upload': 'Asset Upload',
  'Plex Upload Single': 'Asset Upload (Single)',
  'Plex Upload Webhook': 'Asset Upload (Webhook)',
  idarr: 'IDarr',
  maker_monitor: 'Maker Monitor',
  unmatched_assets: 'Unmatched Assets',
  border_replacer: 'Border Replacer',
  artwork_pull: 'Artwork Pull',
}

export const formatJobType = (jobType: string): string =>
  JOB_TYPE_LABELS[jobType] ?? jobType